### ISSUE TITLE
Feature Request : Add common monitoring features

### ISSUE THREAD

**Issue by yukimizake** [bitfocus/companion-module-behringer-xair#12]
Can you add the support of those monitoring (Control Room) commands ?
"CR Mute", "CR Mono" and "CR Dim".

The corresponding OSC commands are : 

/config/solo/mute (0 or 1)
/config/solo/mono (0 or 1)
/config/solo/dim (0 or 1) 

In a broadcast environment those commands are common use, especially to keep the main output constant while your monitoring needs can vary. (Mute the monitoring speakers but not the main output, check mono compatibility of a stereo program and dim the monitoring speakers when you need to talk to other people) 

Thanks

**Comment by McHauge** [comment]
@yukimizake this would be a great additions, would make our setup a lot nicer with it all on the streamdeck. preferably with the same features and feedbacks as for faders.

Maybe also the option to solo inputs would be a nice addition

@istnv maybe that is something you could look at if you have the time on your hands. since you are already deep into the module.

Here are some of the codes for solo:
![image](https://user-images.githubusercontent.com/31018035/88702877-407d7d00-d10c-11ea-819f-a9da29f2c156.png)

here is a link to the codes: https://groups.google.com/forum/#!topic/qlab/rMHbZoY9kTg

**Comment by istnv** [comment]
I was just going to post that I may as well add the entire solo bus on/off as well. (/-stat/solosw/##)
While I see where dim/mute/mono are useful on the fly, the trims and taps end up being more work to program the button than simply using XAir-edit to set them. I'm trying to avoid too much unnecessary bloat.

**Comment by McHauge** [comment]
@istnv totally understand, I was mostly interested in the amility to change the level, and mute/unmute. But being able to clear solo, and solo individual faders would be nice, that way you could program different "presets" by having a button clear all solos, and after that add maybe 2-3 items again, and another button that does the same but with another group.

But the level and mute is most important I would say.

Cheers

**Comment by istnv** [comment]
@McHauge I may not have been clear. I was planning to add the _entire_ solo bus, including channels. Similar to channel mute on/off. Also monitor fader level and clear all. Plus mute/dim/mono as requested.
May take me a day or two since channel indexing is totally different than primary mutes and faders.

**Comment by McHauge** [comment]
@istnv amazing, and yes I mis read it the other way around, would be happy to test it, if I happen to be near our xair when the time comes. 🙌😁
