### ISSUE TITLE
USB Record? XR12

### ISSUE THREAD

**Issue by redimongo** [bitfocus/companion-module-behringer-xair#24]
I am having a small issue setting up a simple record start and stop function.

The X-AIR Edit app does have the function in their so I take it is possible to send the command to the system. I just don't know which option in companion I need to use to set this feature up. I noticed their is no USB record button :).

What I did notice is:

$(xair:f_rtn_aux_d) | USB/Aux In dB | +0.4 -- | -- | --
$(xair:f_rtn_aux_p) | USB/Aux In % | 76
$(xair:l_rtn_aux) | USB/Aux In Label | Aux

So I take it I would need to use $(xair:l_rtn_aux).

I know on the X32 has /-stat/tape/state/4

**Comment by istnv** [comment]
@redimongo Those variables are for the USB playback status. 
The X18 has RCA in/out connectors instead of the USB player/recorder which is the reason for the dual name.
The recording actions are called 'Tape Operation'. Select which operation (Play/Record/Stop) there.
You will need to configure the recording source in XAir Edit.
