### ISSUE TITLE
[FEATURE] Have an option to display 0dB as 100% instead of 75% in instance variable from the console

### ISSUE THREAD

**Issue by Mozoloa** [bitfocus/companion-module-behringer-xair#40]
It would be great to have a way of taking the percent from the variables and doing a rounded operation to make 0dB (75%) show 100% (x1.334 for instance) as I feel it makes more sense since it's 100% on, no amp, no attenuation. That would make the old 100% as 133%, which would make more sense as we're amplifiying past unity.

I prefer dBs but this is for all my clients who don't really understand the concept and have been using consumer products that go up to 100% their whole life. I've already locked my buttons with triggers so they can't go past 0dB so 100% would be the max and would make more sense than 75% max.

**Comment by istnv** [comment]
All reference points changed when analog moved to digital.
It may look similar, but that value is % of the fader position, _not_ % of the output level. 
0dB is correctly at the 75% position of the fader.
It is all relative anyway since you can set input trim and power amp levels to limit the final result, so even at +10dB fader, the actual output is 75% of max.

**Comment by Mozoloa** [comment]
I've actually created an even less confusing and more standard approach to my request, that use perceptual loudness % based around unity gain, you can find it bellow

#42
